import{S as m,a as h}from"./assets/vendor-I6ojcvTw.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function i(a){return a.map(({id:s,webformatURL:r,largeImageURL:n,tags:e,likes:t,views:o,comments:u,downloads:f})=>`<li data-id="${s}" class="gallery-item">
              <a href=${n} class="gallery-link">
              <img src=${r} class="gallery-image" alt=${e}> 
              <div class="wrap"><h2 class="title-like">Likes <span class="span-text"> ${t} </span></h2>
               <h2 class="title-views">Views <span class="span-text"> ${o} </span></h2>
               <h2 class="title-comments">Comments <span class="span-text">${u}</span> </h2>
               <h2 class="title-downloads">Downloads <span class="span-text">${f} </span></h2></div>
  </a>
              </li>`).join("")}const g=new m(".gallery a",{captionDelay:250,captionsData:"alt"}),l=document.querySelector(".gallery"),y="https://pixabay.com/api/",L="47413156-c8c9abea8f6d88937b7892740";document.querySelector(".feedback-form");const d=document.querySelector(".load-more");let c=1;d.addEventListener("click",b);async function p(a){const s=new URLSearchParams({key:L,q:"cat",page:c,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:"true"}),{data:r}=await h(`${y}?${s}`);return r}p().then(a=>{l.insertAdjacentHTML("afterbegin",i(a.hits)),d.classList.replace("load-more-hidden","load-more"),g.refresh()}).catch(a=>alert(a.massage));async function b(){c+=1;try{const a=await p(c);l.insertAdjacentHTML("beforeend",i(a.hits)),console.log(a)}catch(a){alert(a.massage)}}
//# sourceMappingURL=index.js.map
